stages:
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_STRATEGY: fetch

default:
  tags:
    - kcni-docker

.default_before_script: &default_before_script
  - python --version
  - pip --version
  - pip install --upgrade pip build twine

build:wheel:
  stage: build
  image: python:3.13-slim
  before_script:
    - *default_before_script
  script:
    - python -m build
    - ls -l dist
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

publish:gitlab:
  stage: publish
  image: python:3.13-slim
  needs: ["build:wheel"]
  before_script:
    - *default_before_script
  script:
    - TWINE_USERNAME=gitlab-ci-token TWINE_PASSWORD="$CI_JOB_TOKEN" twine upload --repository-url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi" dist/*
  rules:
    - if: $CI_COMMIT_TAG

install:test:
  stage: build
  image: python:3.13-slim
  needs: ["build:wheel"]
  before_script:
    - pip install --upgrade pip
  script:
    - pip install dist/*.whl
    - xnatio --help || python -m xnatio.main --help
  rules:
    - if: $CI_COMMIT_BRANCH 